# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18s30Rc3KAXjg5ZIpGXqqvQJWCIBBT8tt
"""

l=[1,23,4,5,9]
print(l)
l.append(3)
print(l)
l.remove(5)
print(l)

dic={'name':'Mainflow','age':21,'subjects':['Python',"Excel","SQL"]}
print(dic)
dic["Stream"]="Data"
print(dic)
dic.pop("age")
print(dic)

s={1,5,6,3,4}
print(s)
s.add(2)
print(s)
s.remove(3)
print(s)
s.discard(3)
print(s)